name: Verify plugin

on:
  # run on each push
  push:
    branches:
      - main

  # run for pull requests
  pull_request_target:
    branches:
      - main

  # allow manual too
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository files
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Verify plugin
        run: ./gradlew verifyPlugin
